package unipa.uni;
// Generated 29/06/2017 09:18:03 PM by Hibernate Tools 5.1.0.Final


import java.util.Date;

/**
 * EquipoHasServicio generated by hbm2java
 */
public class EquipoHasServicio  implements java.io.Serializable {


     private Integer idEquipoSevicio;
     private Equipo equipo;
     private OrdenServicio ordenServicio;
     private Date fecha;
     private Date hora;

    public EquipoHasServicio() {
    }

    public EquipoHasServicio(Equipo equipo, OrdenServicio ordenServicio, Date fecha, Date hora) {
       this.equipo = equipo;
       this.ordenServicio = ordenServicio;
       this.fecha = fecha;
       this.hora = hora;
    }
   
    public Integer getIdEquipoSevicio() {
        return this.idEquipoSevicio;
    }
    
    public void setIdEquipoSevicio(Integer idEquipoSevicio) {
        this.idEquipoSevicio = idEquipoSevicio;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public OrdenServicio getOrdenServicio() {
        return this.ordenServicio;
    }
    
    public void setOrdenServicio(OrdenServicio ordenServicio) {
        this.ordenServicio = ordenServicio;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHora() {
        return this.hora;
    }
    
    public void setHora(Date hora) {
        this.hora = hora;
    }




}


