package unipa.uni;
// Generated 29/06/2017 09:18:03 PM by Hibernate Tools 5.1.0.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OrdenServicio generated by hbm2java
 */
public class OrdenServicio  implements java.io.Serializable {


     private Integer idOrdenServicio;
     private Servicio servicio;
     private Usuario usuario;
     private Date fecheOrdenSevicio;
     
     private Set<EquipoHasServicio> equipoHasServicios = new HashSet<EquipoHasServicio>(0);

    public OrdenServicio() {
    }

    public OrdenServicio(Servicio servicio, Usuario usuario, Date fecheOrdenSevicio, Set<EquipoHasServicio> equipoHasServicios) {
       this.servicio = servicio;
       this.usuario = usuario;
       this.fecheOrdenSevicio = fecheOrdenSevicio;
       this.equipoHasServicios = equipoHasServicios;
    }
   
    public Integer getIdOrdenServicio() {
        return this.idOrdenServicio;
    }
    
    public void setIdOrdenServicio(Integer idOrdenServicio) {
        this.idOrdenServicio = idOrdenServicio;
    }
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecheOrdenSevicio() {
        return this.fecheOrdenSevicio;
    }
    
    public void setFecheOrdenSevicio(Date fecheOrdenSevicio) {
        this.fecheOrdenSevicio = fecheOrdenSevicio;
    }
    public Set<EquipoHasServicio> getEquipoHasServicios() {
        return this.equipoHasServicios;
    }
    
    public void setEquipoHasServicios(Set<EquipoHasServicio> equipoHasServicios) {
        this.equipoHasServicios = equipoHasServicios;
    }




}


