package unipa.uni;
// Generated 29/06/2017 09:18:03 PM by Hibernate Tools 5.1.0.Final


import java.util.HashSet;
import java.util.Set;

/**
 * TipoDocumento generated by hbm2java
 */
public class TipoDocumento  implements java.io.Serializable {


     private Integer idTipoDocumento;
     private String tipoDocumento;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public TipoDocumento() {
    }

	
    public TipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public TipoDocumento(String tipoDocumento, Set<Usuario> usuarios) {
       this.tipoDocumento = tipoDocumento;
       this.usuarios = usuarios;
    }
   
    public Integer getIdTipoDocumento() {
        return this.idTipoDocumento;
    }
    
    public void setIdTipoDocumento(Integer idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


