package unipa.uni;
// Generated 29/06/2017 09:18:03 PM by Hibernate Tools 5.1.0.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Rol rol;
     private TipoDocumento tipoDocumento;
     private String nombreUsuario;
     private String contrasenaUsuario;
     private String direccion;
     private Integer telefono;
     private String documento;
     private Set<OrdenServicio> ordenServicios = new HashSet<OrdenServicio>(0);

    public Usuario() {
    }

	
    public Usuario(String nombreUsuario, String contrasenaUsuario, String documento) {
        this.nombreUsuario = nombreUsuario;
        this.contrasenaUsuario = contrasenaUsuario;
        this.documento = documento;
    }
    public Usuario(Rol rol, TipoDocumento tipoDocumento, String nombreUsuario, String contrasenaUsuario, String direccion, Integer telefono, String documento, Set<OrdenServicio> ordenServicios) {
       this.rol = rol;
       this.tipoDocumento = tipoDocumento;
       this.nombreUsuario = nombreUsuario;
       this.contrasenaUsuario = contrasenaUsuario;
       this.direccion = direccion;
       this.telefono = telefono;
       this.documento = documento;
       this.ordenServicios = ordenServicios;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public TipoDocumento getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(TipoDocumento tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasenaUsuario() {
        return this.contrasenaUsuario;
    }
    
    public void setContrasenaUsuario(String contrasenaUsuario) {
        this.contrasenaUsuario = contrasenaUsuario;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public Set<OrdenServicio> getOrdenServicios() {
        return this.ordenServicios;
    }
    
    public void setOrdenServicios(Set<OrdenServicio> ordenServicios) {
        this.ordenServicios = ordenServicios;
    }




}


